Repository schubergphilis/terraform-aws-mcaf-ses-forwarder, pull requests merged in 2024-09, with the labels that each got.

#18 fix: fix for central workflow files
  .github/workflows/terraform.yml
  .gitignore
  CHANGELOG.MD
  README.md
  examples/basic/main.tf
  examples/basic/versions.tf
  variables.tf
Labels: bug, documentation

#16 bug: Fix incoming mail rule when catching all mail for a domain
  README.md
  main.tf
Labels: bug

#17 feature: update for nodejs18
  README.md
  examples/basic/main.tf
  examples/basic/versions.tf
  lambda.tf
  lambda/index.js.tftpl
  s3.tf
  versions.tf
Labels: feature

#19 bugfix: nodejs20 support
  lambda.tf
  lambda/index.js
Labels: bug
